# Makefile for RISC-V Assembly

# Compiler and Linker
RISCV=gcc-riscv64-linux-gnu-
AS=as-riscv64-linux-gnu-
LD=ld-lm32-elf-

# Flags
CFLAGS=-g -Os -ffreestanding
LDFLAGS=-T linker.ld

# Targets
all: main.hex

main.hex: main.o
	$(RISCV)$(LD) $(LDFLAGS) -o main.bin main.o
	riscv64-linux-gnu-objcopy -O ihex main.bin main.hex

main.o: main.s
	$(AS) $(CFLAGS) main.s -o main.o

clean:
	rm -f *.o *.bin *.hex
